// Ghidra script: DiUSB20 driver layer decompilation via string cross-references
// Finds functions containing DiUSB20 module name strings, decompiles with depth 2
// Collects all 0xC022xxxx USB register accesses to build register map
// Output: firmware-analysis/usb_driver_decompiled.txt
//
// Run headlessly:
//   analyzeHeadless C:\projects\ixus870IS\firmware-analysis\ghidra_project ixus870_101a
//     -process PRIMARY.BIN -noanalysis -scriptPath C:\projects\ixus870IS\firmware-analysis
//     -postScript DecompileUSBDriver.java
// @category Analysis

import ghidra.app.script.GhidraScript;
import ghidra.app.decompiler.DecompInterface;
import ghidra.app.decompiler.DecompileResults;
import ghidra.program.model.listing.Function;
import ghidra.program.model.listing.FunctionManager;
import ghidra.program.model.listing.Instruction;
import ghidra.program.model.listing.InstructionIterator;
import ghidra.program.model.address.Address;
import ghidra.program.model.address.AddressSet;
import ghidra.program.model.mem.Memory;
import ghidra.program.model.symbol.Reference;
import ghidra.program.model.symbol.ReferenceIterator;

import java.io.*;
import java.util.*;

public class DecompileUSBDriver extends GhidraScript {

    private DecompInterface decomp;
    private Set<Long> visited = new HashSet<>();
    private StringBuilder output = new StringBuilder();
    private int successCount = 0;
    private int failCount = 0;
    private Map<String, String> usbRegisterMap = new TreeMap<>();

    // DiUSB20 module strings to search for
    private static final String[] MODULE_STRINGS = {
        "DiUSB20DM.c",        // Device Manager
        "DiUSB20Hal.c",       // Hardware Abstraction Layer
        "DiUSB20HDMACHal.c",  // DMA Controller HAL
        "DiUSB20CP.c",        // Control Pipe (EP0)
        "DiUSB20DP.c",        // Data Pipe (bulk/interrupt endpoints)
        "DianaUSBConfig.c",   // USB configuration/descriptors
    };

    // OS primitives — don't recurse
    private static final Set<Long> OS_PRIMITIVES = new HashSet<>(Arrays.asList(
        0xFF81099CL,  // msleep
        0xFF827098L,  // ReceiveMessageQueue
        0xFF8279ECL,  // TryPostMessageQueue
        0xFF827584L,  // GiveSemaphore
        0xFF8274C4L,  // TakeSemaphore
        0xFF811A2CL,  // CreateTask
        0xFF8269D0L,  // CreateMessageQueue
        0xFF82708CL   // DeleteMessageQueue
    ));

    private static final int MAX_DEPTH = 2;

    @Override
    public void run() throws Exception {
        decomp = new DecompInterface();
        decomp.openProgram(currentProgram);
        decomp.setSimplificationStyle("decompile");

        output.append("=======================================================================\n");
        output.append("DiUSB20 Driver Layer — String-Based Decompilation (2-level depth)\n");
        output.append("Firmware: Canon IXUS 870 IS / SD880 IS, version 1.01a\n");
        output.append("Generated by DecompileUSBDriver.java (Ghidra headless)\n");
        output.append("Focus: DiUSB20 modules, USB register map, endpoint configuration\n");
        output.append("=======================================================================\n\n");

        output.append("KEY QUESTIONS:\n");
        output.append("1. What USB controller IP core is this? (MUSB vs DWC vs custom)\n");
        output.append("2. How many hardware endpoints exist?\n");
        output.append("3. Is isochronous transfer supported at hardware level?\n");
        output.append("4. How are endpoint types configured?\n\n");

        // For each module string, find it in memory and decompile referencing functions
        for (String modStr : MODULE_STRINGS) {
            output.append("\n\n");
            output.append("***************************************************************\n");
            output.append("MODULE: " + modStr + "\n");
            output.append("***************************************************************\n");

            List<Address> stringAddrs = findStringInMemory(modStr);
            if (stringAddrs.isEmpty()) {
                output.append("  STRING NOT FOUND in firmware memory!\n");
                continue;
            }

            for (Address strAddr : stringAddrs) {
                output.append(String.format("  String found at: 0x%s\n", strAddr));

                // Find all references to this string address
                Set<Function> referencingFunctions = findFunctionsReferencing(strAddr);

                if (referencingFunctions.isEmpty()) {
                    // Try finding references to a pointer that points to this string
                    output.append("  No direct xrefs. Scanning for pointer references...\n");
                    referencingFunctions = findFunctionsViaPointer(strAddr);
                }

                if (referencingFunctions.isEmpty()) {
                    output.append("  No referencing functions found.\n");
                    // Still try to decompile the function AT or NEAR this address
                    Function nearFunc = findNearestFunction(strAddr);
                    if (nearFunc != null) {
                        output.append(String.format("  Nearest function: %s @ 0x%s\n",
                            nearFunc.getName(), nearFunc.getEntryPoint()));
                        decompileAt(nearFunc.getEntryPoint().getOffset(), 0);
                    }
                } else {
                    output.append(String.format("  Found %d referencing functions:\n", referencingFunctions.size()));
                    for (Function func : referencingFunctions) {
                        output.append(String.format("    %s @ 0x%s\n",
                            func.getName(), func.getEntryPoint()));
                    }
                    // Decompile each referencing function
                    for (Function func : referencingFunctions) {
                        decompileAt(func.getEntryPoint().getOffset(), 0);
                    }
                }
            }
        }

        // Global USB register scan: find ALL functions that access 0xC022xxxx
        output.append("\n\n=======================================================================\n");
        output.append("GLOBAL SCAN: All 0xC022xxxx USB register accesses in firmware\n");
        output.append("=======================================================================\n");
        scanAllUSBRegisters();

        // USB register map summary
        output.append("\n\n=======================================================================\n");
        output.append("USB REGISTER MAP (0xC022xxxx)\n");
        output.append("=======================================================================\n");
        if (usbRegisterMap.isEmpty()) {
            output.append("  (no 0xC022xxxx registers found)\n");
        } else {
            for (Map.Entry<String, String> entry : usbRegisterMap.entrySet()) {
                output.append(String.format("  %s — %s\n", entry.getKey(), entry.getValue()));
            }
        }

        // Summary
        output.append(String.format("\n\n=== SUMMARY: %d functions decompiled, %d failed ===\n",
                      successCount, failCount));

        // Write output
        String outDir = getSourceFile().getParentFile().getAbsolutePath();
        String outPath = outDir + File.separator + "usb_driver_decompiled.txt";
        PrintWriter pw = new PrintWriter(new FileWriter(outPath));
        pw.print(output.toString());
        pw.close();

        decomp.dispose();
        printf("Wrote %d chars (%d functions, %d failed) to %s%n",
               output.length(), successCount, failCount, outPath);
    }

    private List<Address> findStringInMemory(String searchStr) {
        List<Address> results = new ArrayList<>();
        Memory mem = currentProgram.getMemory();
        byte[] pattern = searchStr.getBytes();
        Address start = currentProgram.getMinAddress();
        Address maxAddr = currentProgram.getMaxAddress();
        try {
            while (start != null && start.compareTo(maxAddr) < 0) {
                Address found = mem.findBytes(start, pattern, null, true, monitor);
                if (found == null) break;
                results.add(found);
                if (found.compareTo(maxAddr.subtract(1)) >= 0) break;
                try { start = found.add(1); } catch (Exception e2) { break; }
            }
        } catch (Exception e) {
            output.append("  Error searching for string: " + e.getMessage() + "\n");
        }
        return results;
    }

    private Set<Function> findFunctionsReferencing(Address addr) {
        Set<Function> funcs = new LinkedHashSet<>();
        FunctionManager fm = currentProgram.getFunctionManager();
        ReferenceIterator refs = currentProgram.getReferenceManager().getReferencesTo(addr);
        while (refs.hasNext()) {
            Reference ref = refs.next();
            Function func = fm.getFunctionContaining(ref.getFromAddress());
            if (func != null) {
                funcs.add(func);
            }
        }
        return funcs;
    }

    private Set<Function> findFunctionsViaPointer(Address strAddr) {
        // Search for 4-byte little-endian pointers to this string address
        Set<Function> funcs = new LinkedHashSet<>();
        long addrVal = strAddr.getOffset();
        byte[] ptrBytes = new byte[] {
            (byte)(addrVal & 0xFF),
            (byte)((addrVal >> 8) & 0xFF),
            (byte)((addrVal >> 16) & 0xFF),
            (byte)((addrVal >> 24) & 0xFF)
        };

        Memory mem = currentProgram.getMemory();
        Address start = currentProgram.getMinAddress();
        Address maxAddr = currentProgram.getMaxAddress();
        try {
            int found_count = 0;
            while (start != null && found_count < 50 && start.compareTo(maxAddr) < 0) {
                Address found = mem.findBytes(start, ptrBytes, null, true, monitor);
                if (found == null) break;
                found_count++;

                // Check if anyone references THIS pointer location
                ReferenceIterator refs = currentProgram.getReferenceManager().getReferencesTo(found);
                while (refs.hasNext()) {
                    Reference ref = refs.next();
                    Function func = currentProgram.getFunctionManager().getFunctionContaining(ref.getFromAddress());
                    if (func != null) funcs.add(func);
                }

                try { start = found.add(1); } catch (Exception e2) { break; }
            }
        } catch (Exception e) {
            // ignore
        }
        return funcs;
    }

    private Function findNearestFunction(Address addr) {
        FunctionManager fm = currentProgram.getFunctionManager();
        // Check if addr is inside a function
        Function func = fm.getFunctionContaining(addr);
        if (func != null) return func;

        // Search backwards for the nearest function start
        Address search = addr;
        for (int i = 0; i < 2048; i++) {
            search = search.subtract(1);
            func = fm.getFunctionAt(search);
            if (func != null) return func;
        }
        return null;
    }

    private void decompileAt(long addr, int depth) {
        if (visited.contains(addr)) return;
        if (depth > MAX_DEPTH) return;
        visited.add(addr);

        Address address = toAddr(addr);
        FunctionManager fm = currentProgram.getFunctionManager();
        Function func = fm.getFunctionAt(address);

        if (func == null) {
            output.append(String.format("\n// No function at 0x%08X (depth=%d)\n", addr, depth));
            failCount++;
            return;
        }

        // Header
        String indent = depth == 0 ? "========" : (depth == 1 ? "--------" : "........");
        output.append("\n\n");
        output.append(indent + indent + indent + indent + indent + "\n");
        output.append(String.format("Function: %s @ 0x%08X (size=%d bytes, depth=%d)\n",
                      func.getName(), addr, func.getBody().getNumAddresses(), depth));
        output.append(indent + indent + indent + indent + indent + "\n");

        // Callers
        Set<Function> callers = func.getCallingFunctions(monitor);
        if (!callers.isEmpty()) {
            output.append("// Called from:\n");
            int shown = 0;
            for (Function caller : callers) {
                if (shown >= 15) {
                    output.append(String.format("//   ... and %d more callers\n", callers.size() - shown));
                    break;
                }
                output.append(String.format("//   0x%s (%s)\n",
                    caller.getEntryPoint(), caller.getName()));
                shown++;
            }
        }

        // Callees
        Set<Function> callees = func.getCalledFunctions(monitor);
        if (!callees.isEmpty()) {
            output.append("// Calls:\n");
            for (Function callee : callees) {
                output.append(String.format("//   0x%s (%s)\n",
                    callee.getEntryPoint(), callee.getName()));
            }
        }
        output.append("\n");

        // Decompile
        DecompileResults results = decomp.decompileFunction(func, 60, monitor);
        if (results == null || !results.decompileCompleted()) {
            output.append(String.format("// DECOMPILATION FAILED: %s\n",
                results != null ? results.getErrorMessage() : "null result"));
            failCount++;
            return;
        }

        String cCode = results.getDecompiledFunction().getC();
        output.append(cCode);
        successCount++;

        // Scan for USB registers and function pointers
        scanReferences(func);

        // Recurse into callees
        if (depth < MAX_DEPTH) {
            for (Function callee : callees) {
                long calleeAddr = callee.getEntryPoint().getOffset();
                if (calleeAddr < 0xFF800000L) continue;
                if (depth > 0 && OS_PRIMITIVES.contains(calleeAddr)) continue;
                decompileAt(calleeAddr, depth + 1);
            }
        }
    }

    private void scanReferences(Function func) {
        try {
            InstructionIterator instIter =
                currentProgram.getListing().getInstructions(func.getBody(), true);
            Set<String> ptrs = new TreeSet<>();
            while (instIter.hasNext()) {
                Instruction inst = instIter.next();
                Reference[] refs = inst.getReferencesFrom();
                for (Reference ref : refs) {
                    long target = ref.getToAddress().getOffset();

                    // USB register accesses (0xC022xxxx)
                    if ((target & 0xFFFF0000L) == 0xC0220000L) {
                        String regKey = String.format("0x%08X", target);
                        String regVal = String.format("accessed in %s @ 0x%s (inst: %s)",
                            func.getName(), inst.getAddress(), inst.toString());
                        usbRegisterMap.put(regKey, regVal);
                    }

                    // Function pointer loads from data references
                    if (ref.getReferenceType().isData() &&
                        target >= 0xFF800000L && target < 0xFFF00000L) {
                        try {
                            byte[] bytes = new byte[4];
                            currentProgram.getMemory().getBytes(ref.getToAddress(), bytes);
                            long val = (bytes[0] & 0xFFL) | ((bytes[1] & 0xFFL) << 8) |
                                       ((bytes[2] & 0xFFL) << 16) | ((bytes[3] & 0xFFL) << 24);
                            // Check for USB register in loaded value
                            if ((val & 0xFFFF0000L) == 0xC0220000L) {
                                String regKey = String.format("0x%08X", val);
                                String regVal = String.format("loaded via DAT_%08x in %s",
                                    target, func.getName());
                                usbRegisterMap.put(regKey, regVal);
                            }
                            // Function pointers
                            if (val >= 0xFF800000L && val < 0xFFF00000L) {
                                FunctionManager fm = currentProgram.getFunctionManager();
                                Function fpFunc = fm.getFunctionAt(toAddr(val));
                                String name = fpFunc != null ? fpFunc.getName() : "unknown";
                                ptrs.add(String.format("DAT_%08x = 0x%08X (%s)",
                                         target, val, name));
                            }
                        } catch (Exception e) { /* ignore */ }
                    }
                }
            }
            if (!ptrs.isEmpty()) {
                output.append("// Function pointer references found:\n");
                for (String p : ptrs) {
                    output.append("//   " + p + "\n");
                }
            }
        } catch (Exception e) {
            output.append("// Error scanning references: " + e.getMessage() + "\n");
        }
    }

    private void scanAllUSBRegisters() {
        // Search for all 4-byte values in the 0xC022xxxx range stored in ROM
        // These are typically loaded via LDR Rx, =0xC022xxxx (constant pool entries)
        Memory mem = currentProgram.getMemory();
        FunctionManager fm = currentProgram.getFunctionManager();

        // Search for 0xC022 as the upper 16 bits (little-endian: xx xx 22 C0)
        byte[] pattern = new byte[] { 0x00, 0x00, 0x22, (byte)0xC0 };
        byte[] mask    = new byte[] { 0x00, 0x00, (byte)0xFF, (byte)0xFF };

        Address start = currentProgram.getMinAddress();
        Address maxAddr = currentProgram.getMaxAddress();
        int count = 0;
        try {
            while (start != null && count < 500 && start.compareTo(maxAddr) < 0) {
                Address found = mem.findBytes(start, pattern, mask, true, monitor);
                if (found == null) break;

                byte[] bytes = new byte[4];
                mem.getBytes(found, bytes);
                long val = (bytes[0] & 0xFFL) | ((bytes[1] & 0xFFL) << 8) |
                           ((bytes[2] & 0xFFL) << 16) | ((bytes[3] & 0xFFL) << 24);

                if ((val & 0xFFFF0000L) == 0xC0220000L) {
                    // Find what function references this constant pool entry
                    ReferenceIterator refs = currentProgram.getReferenceManager().getReferencesTo(found);
                    while (refs.hasNext()) {
                        Reference ref = refs.next();
                        Function func = fm.getFunctionContaining(ref.getFromAddress());
                        String funcName = func != null ? func.getName() : "unknown";
                        String regKey = String.format("0x%08X", val);
                        if (!usbRegisterMap.containsKey(regKey)) {
                            usbRegisterMap.put(regKey, String.format("used in %s @ 0x%s",
                                funcName, ref.getFromAddress()));
                        }
                        output.append(String.format("  0x%08X at ROM 0x%s, referenced by %s @ 0x%s\n",
                            val, found, funcName, ref.getFromAddress()));
                    }
                    count++;
                }
                try { start = found.add(4); } catch (Exception e2) { break; }
            }
        } catch (Exception e) {
            output.append("  Error during global scan: " + e.getMessage() + "\n");
        }
        output.append(String.format("  Total: %d unique 0xC022xxxx values found\n", count));
    }

    private void printCallers(long addr) {
        Address address = toAddr(addr);
        ReferenceIterator refIter = currentProgram.getReferenceManager().getReferencesTo(address);
        int count = 0;
        while (refIter.hasNext()) {
            Reference ref = refIter.next();
            Function caller = currentProgram.getFunctionManager().getFunctionContaining(ref.getFromAddress());
            String callerName = caller != null ? caller.getName() : "unknown";
            output.append(String.format("  0x%s in %s (type=%s)\n",
                ref.getFromAddress(), callerName, ref.getReferenceType()));
            count++;
        }
        if (count == 0) {
            output.append("  (no references found)\n");
        }
        output.append(String.format("  Total: %d references\n", count));
    }
}
