// Ghidra script: USB Protocol switching, PTP handler registration, PTP session task
// Targets: handle_PTP_OC_CANON_ChangeUSBProtocol, add_ptp_handler, task_PTPSessionTASK
// Depth: 3 levels of callee recursion
// Output: firmware-analysis/usb_protocol_decompiled.txt
//
// Run headlessly:
//   analyzeHeadless C:\projects\ixus870IS\firmware-analysis\ghidra_project ixus870_101a
//     -process PRIMARY.BIN -noanalysis -scriptPath C:\projects\ixus870IS\firmware-analysis
//     -postScript DecompileUSBProtocol.java
// @category Analysis

import ghidra.app.script.GhidraScript;
import ghidra.app.decompiler.DecompInterface;
import ghidra.app.decompiler.DecompileResults;
import ghidra.program.model.listing.Function;
import ghidra.program.model.listing.FunctionManager;
import ghidra.program.model.listing.Instruction;
import ghidra.program.model.listing.InstructionIterator;
import ghidra.program.model.address.Address;
import ghidra.program.model.symbol.Reference;
import ghidra.program.model.symbol.ReferenceIterator;

import java.io.*;
import java.util.*;

public class DecompileUSBProtocol extends GhidraScript {

    private DecompInterface decomp;
    private Set<Long> visited = new HashSet<>();
    private StringBuilder output = new StringBuilder();
    private int successCount = 0;
    private int failCount = 0;
    private Set<String> usbRegisters = new TreeSet<>();

    // Primary targets
    private static final long[] PRIMARY_TARGETS = {
        0xFF9F02E4L,  // handle_PTP_OC_CANON_ChangeUSBProtocol — USB mode switching
        0xFF9EF744L,  // add_ptp_handler — PTP handler registration
        0xFF8CD448L,  // task_PTPSessionTASK — main PTP/USB control loop
    };

    // OS primitives — decompile body but don't recurse into callees
    private static final Set<Long> OS_PRIMITIVES = new HashSet<>(Arrays.asList(
        0xFF81099CL,  // msleep / SleepTask
        0xFF827098L,  // ReceiveMessageQueue
        0xFF8279ECL,  // TryPostMessageQueue
        0xFF827584L,  // GiveSemaphore
        0xFF8274C4L,  // TakeSemaphore
        0xFF811A2CL,  // CreateTask
        0xFF8269D0L,  // CreateMessageQueue
        0xFF82708CL   // DeleteMessageQueue
    ));

    private static final int MAX_DEPTH = 3;

    @Override
    public void run() throws Exception {
        decomp = new DecompInterface();
        decomp.openProgram(currentProgram);
        decomp.setSimplificationStyle("decompile");

        output.append("=======================================================================\n");
        output.append("USB Protocol Switching & PTP Session — Decompilation (3-level depth)\n");
        output.append("Firmware: Canon IXUS 870 IS / SD880 IS, version 1.01a\n");
        output.append("Generated by DecompileUSBProtocol.java (Ghidra headless)\n");
        output.append("Focus: ChangeUSBProtocol, add_ptp_handler, task_PTPSessionTASK\n");
        output.append("=======================================================================\n\n");

        output.append("KEY QUESTIONS:\n");
        output.append("1. Does ChangeUSBProtocol trigger USB re-enumeration (soft disconnect/reconnect)?\n");
        output.append("2. Are USB descriptors copied to RAM (modifiable) or served from ROM?\n");
        output.append("3. How are PTP handlers registered? Can we add custom UVC handlers?\n");
        output.append("4. What is the PTP session lifecycle?\n\n");

        // Decompile all primary targets
        for (long addr : PRIMARY_TARGETS) {
            decompileAt(addr, 0);
        }

        // Cross-references: who calls ChangeUSBProtocol?
        output.append("\n\n=======================================================================\n");
        output.append("CROSS-REFERENCE: All callers of ChangeUSBProtocol (0xFF9F02E4)\n");
        output.append("=======================================================================\n");
        printCallers(0xFF9F02E4L);

        // Cross-references: who calls add_ptp_handler?
        output.append("\n=======================================================================\n");
        output.append("CROSS-REFERENCE: All callers of add_ptp_handler (0xFF9EF744)\n");
        output.append("=======================================================================\n");
        printCallers(0xFF9EF744L);

        // USB register summary
        output.append("\n\n=======================================================================\n");
        output.append("USB REGISTER MAP (0xC022xxxx accesses found in decompiled functions)\n");
        output.append("=======================================================================\n");
        if (usbRegisters.isEmpty()) {
            output.append("  (no 0xC022xxxx registers accessed in these functions)\n");
        } else {
            for (String reg : usbRegisters) {
                output.append("  " + reg + "\n");
            }
        }

        // Summary
        output.append(String.format("\n\n=== SUMMARY: %d functions decompiled, %d failed ===\n",
                      successCount, failCount));

        // Write output
        String outDir = getSourceFile().getParentFile().getAbsolutePath();
        String outPath = outDir + File.separator + "usb_protocol_decompiled.txt";
        PrintWriter pw = new PrintWriter(new FileWriter(outPath));
        pw.print(output.toString());
        pw.close();

        decomp.dispose();
        printf("Wrote %d chars (%d functions, %d failed) to %s%n",
               output.length(), successCount, failCount, outPath);
    }

    private void decompileAt(long addr, int depth) {
        if (visited.contains(addr)) return;
        if (depth > MAX_DEPTH) return;
        visited.add(addr);

        Address address = toAddr(addr);
        FunctionManager fm = currentProgram.getFunctionManager();
        Function func = fm.getFunctionAt(address);

        if (func == null) {
            output.append(String.format("\n// No function at 0x%08X (depth=%d)\n", addr, depth));
            failCount++;
            return;
        }

        // Header
        String indent = depth == 0 ? "========" : (depth == 1 ? "--------" : "........");
        output.append("\n\n");
        output.append(indent + indent + indent + indent + indent + "\n");
        output.append(String.format("Function: %s @ 0x%08X (size=%d bytes, depth=%d)\n",
                      func.getName(), addr, func.getBody().getNumAddresses(), depth));
        output.append(indent + indent + indent + indent + indent + "\n");

        // Callers
        Set<Function> callers = func.getCallingFunctions(monitor);
        if (!callers.isEmpty()) {
            output.append("// Called from:\n");
            int shown = 0;
            for (Function caller : callers) {
                if (shown >= 15) {
                    output.append(String.format("//   ... and %d more callers\n", callers.size() - shown));
                    break;
                }
                output.append(String.format("//   0x%s (%s)\n",
                    caller.getEntryPoint(), caller.getName()));
                shown++;
            }
        }

        // Callees
        Set<Function> callees = func.getCalledFunctions(monitor);
        if (!callees.isEmpty()) {
            output.append("// Calls:\n");
            for (Function callee : callees) {
                output.append(String.format("//   0x%s (%s)\n",
                    callee.getEntryPoint(), callee.getName()));
            }
        }
        output.append("\n");

        // Decompile
        DecompileResults results = decomp.decompileFunction(func, 60, monitor);
        if (results == null || !results.decompileCompleted()) {
            output.append(String.format("// DECOMPILATION FAILED: %s\n",
                results != null ? results.getErrorMessage() : "null result"));
            failCount++;
            return;
        }

        String cCode = results.getDecompiledFunction().getC();
        output.append(cCode);
        successCount++;

        // Scan for function pointer loads and USB registers
        scanReferences(func);

        // Recurse into callees
        if (depth < MAX_DEPTH) {
            for (Function callee : callees) {
                long calleeAddr = callee.getEntryPoint().getOffset();
                if (calleeAddr < 0xFF800000L) continue;
                if (depth > 0 && OS_PRIMITIVES.contains(calleeAddr)) continue;
                decompileAt(calleeAddr, depth + 1);
            }
        }
    }

    private void scanReferences(Function func) {
        try {
            InstructionIterator instIter =
                currentProgram.getListing().getInstructions(func.getBody(), true);
            Set<String> ptrs = new TreeSet<>();
            while (instIter.hasNext()) {
                Instruction inst = instIter.next();
                Reference[] refs = inst.getReferencesFrom();
                for (Reference ref : refs) {
                    long target = ref.getToAddress().getOffset();

                    // USB register accesses (0xC022xxxx)
                    if ((target & 0xFFFF0000L) == 0xC0220000L) {
                        String entry = String.format("0x%08X (in %s @ 0x%s)",
                            target, func.getName(), func.getEntryPoint());
                        usbRegisters.add(entry);
                    }

                    // Function pointer loads
                    if (ref.getReferenceType().isData() &&
                        target >= 0xFF800000L && target < 0xFFF00000L) {
                        try {
                            byte[] bytes = new byte[4];
                            currentProgram.getMemory().getBytes(ref.getToAddress(), bytes);
                            long val = (bytes[0] & 0xFFL) | ((bytes[1] & 0xFFL) << 8) |
                                       ((bytes[2] & 0xFFL) << 16) | ((bytes[3] & 0xFFL) << 24);
                            if (val >= 0xFF800000L && val < 0xFFF00000L) {
                                FunctionManager fm = currentProgram.getFunctionManager();
                                Function fpFunc = fm.getFunctionAt(toAddr(val));
                                String name = fpFunc != null ? fpFunc.getName() : "unknown";
                                ptrs.add(String.format("DAT_%08x = 0x%08X (%s)",
                                         target, val, name));
                            }
                            // Also check if the loaded value is a USB register
                            if ((val & 0xFFFF0000L) == 0xC0220000L) {
                                String entry = String.format("0x%08X (indirect via DAT_%08x in %s)",
                                    val, target, func.getName());
                                usbRegisters.add(entry);
                            }
                        } catch (Exception e) { /* ignore */ }
                    }
                }
            }
            if (!ptrs.isEmpty()) {
                output.append("// Function pointer references found:\n");
                for (String p : ptrs) {
                    output.append("//   " + p + "\n");
                }
            }
        } catch (Exception e) {
            output.append("// Error scanning references: " + e.getMessage() + "\n");
        }
    }

    private void printCallers(long addr) {
        Address address = toAddr(addr);
        ReferenceIterator refIter = currentProgram.getReferenceManager().getReferencesTo(address);
        int count = 0;
        while (refIter.hasNext()) {
            Reference ref = refIter.next();
            Function caller = currentProgram.getFunctionManager().getFunctionContaining(ref.getFromAddress());
            String callerName = caller != null ? caller.getName() : "unknown";
            output.append(String.format("  0x%s in %s (type=%s)\n",
                ref.getFromAddress(), callerName, ref.getReferenceType()));
            count++;
        }
        if (count == 0) {
            output.append("  (no references found)\n");
        }
        output.append(String.format("  Total: %d references\n", count));
    }
}
