// Ghidra script: USB transport controller — class request dispatcher + bulk transfer
// Finds functions via string cross-references: ClassRequest, AsyncWrite, BulkTrns
// Output: firmware-analysis/usb_transport_decompiled.txt
//
// Run headlessly:
//   analyzeHeadless C:\projects\ixus870IS\firmware-analysis\ghidra_project ixus870_101a
//     -process PRIMARY.BIN -noanalysis -scriptPath C:\projects\ixus870IS\firmware-analysis
//     -postScript DecompileUSBTransport.java
// @category Analysis

import ghidra.app.script.GhidraScript;
import ghidra.app.decompiler.DecompInterface;
import ghidra.app.decompiler.DecompileResults;
import ghidra.program.model.listing.Function;
import ghidra.program.model.listing.FunctionManager;
import ghidra.program.model.listing.Instruction;
import ghidra.program.model.listing.InstructionIterator;
import ghidra.program.model.address.Address;
import ghidra.program.model.mem.Memory;
import ghidra.program.model.symbol.Reference;
import ghidra.program.model.symbol.ReferenceIterator;

import java.io.*;
import java.util.*;

public class DecompileUSBTransport extends GhidraScript {

    private DecompInterface decomp;
    private Set<Long> visited = new HashSet<>();
    private StringBuilder output = new StringBuilder();
    private int successCount = 0;
    private int failCount = 0;
    private Set<String> usbRegisters = new TreeSet<>();

    // Transport strings to search for — each identifies a key function
    private static final String[][] TRANSPORT_STRINGS = {
        {"ClassRequest, bRequest=%#02x", "Class request dispatcher — where UVC requests would be handled"},
        {"AsyncWriteUSBDataPipeMulti Error", "Multi-buffer bulk write — could stream video frames"},
        {"AsyncWriteUSBDataPipe Error", "Single-buffer bulk write"},
        {"BulkTrns.c", "Bulk transport implementation module"},
        {"AsyncReadUSBDataPipe", "Bulk read (host→device)"},
        {"CancelUSBDataPipe", "Cancel pending USB transfer"},
        {"StallUSBDataPipe", "Stall endpoint (error signaling)"},
        {"USBDataPipeEvent", "Data pipe event handling"},
    };

    // Additional strings related to USB control and class handling
    private static final String[][] CONTROL_STRINGS = {
        {"SetInterface", "USB SET_INTERFACE request handler"},
        {"SET_INTERFACE", "SET_INTERFACE request handler (alternate)"},
        {"GetInterface", "USB GET_INTERFACE request handler"},
        {"ClearFeature", "USB CLEAR_FEATURE request handler"},
        {"SetFeature", "USB SET_FEATURE request handler"},
        {"EP0", "Endpoint 0 control pipe"},
    };

    // OS primitives
    private static final Set<Long> OS_PRIMITIVES = new HashSet<>(Arrays.asList(
        0xFF81099CL, 0xFF827098L, 0xFF8279ECL, 0xFF827584L,
        0xFF8274C4L, 0xFF811A2CL, 0xFF8269D0L, 0xFF82708CL
    ));

    private static final int MAX_DEPTH = 2;

    @Override
    public void run() throws Exception {
        decomp = new DecompInterface();
        decomp.openProgram(currentProgram);
        decomp.setSimplificationStyle("decompile");

        output.append("=======================================================================\n");
        output.append("USB Transport Controller — Class Request & Bulk Transfer Decompilation\n");
        output.append("Firmware: Canon IXUS 870 IS / SD880 IS, version 1.01a\n");
        output.append("Generated by DecompileUSBTransport.java (Ghidra headless)\n");
        output.append("Focus: ClassRequest handler, AsyncWrite, BulkTrns\n");
        output.append("=======================================================================\n\n");

        output.append("KEY QUESTIONS:\n");
        output.append("1. Can we hook the class request dispatcher for UVC requests?\n");
        output.append("2. Can AsyncWriteUSBDataPipeMulti stream video frames through bulk EP?\n");
        output.append("3. What is the bulk transfer buffer management model?\n");
        output.append("4. How are endpoints opened/configured for data transfer?\n\n");

        // === Transport strings ===
        output.append("=======================================================================\n");
        output.append("SECTION 1: Transport Functions (via string xrefs)\n");
        output.append("=======================================================================\n");

        for (String[] entry : TRANSPORT_STRINGS) {
            findAndDecompileByString(entry[0], entry[1]);
        }

        // === Control strings ===
        output.append("\n\n=======================================================================\n");
        output.append("SECTION 2: USB Control Request Handlers (via string xrefs)\n");
        output.append("=======================================================================\n");

        for (String[] entry : CONTROL_STRINGS) {
            findAndDecompileByString(entry[0], entry[1]);
        }

        // === Scan for USB reset/reconnect functions ===
        output.append("\n\n=======================================================================\n");
        output.append("SECTION 3: USB Disconnect/Reconnect Functions\n");
        output.append("=======================================================================\n");

        String[][] disconnectStrings = {
            {"Disconnect", "USB disconnect handling"},
            {"SoftConnect", "Software connect/disconnect control"},
            {"USBReset", "USB bus reset"},
            {"BusReset", "Bus reset handler"},
            {"Enumerat", "USB enumeration"},
            {"ReEnumerat", "USB re-enumeration"},
        };

        for (String[] entry : disconnectStrings) {
            findAndDecompileByString(entry[0], entry[1]);
        }

        // === USB register summary ===
        output.append("\n\n=======================================================================\n");
        output.append("USB REGISTER MAP (0xC022xxxx accesses in transport functions)\n");
        output.append("=======================================================================\n");
        if (usbRegisters.isEmpty()) {
            output.append("  (no 0xC022xxxx registers found)\n");
        } else {
            for (String reg : usbRegisters) {
                output.append("  " + reg + "\n");
            }
        }

        // === Cross-references for key functions ===
        output.append("\n\n=======================================================================\n");
        output.append("SECTION 4: Cross-references for async write functions\n");
        output.append("=======================================================================\n");

        // Find AsyncWriteUSBDataPipeMulti function and list all callers
        List<Address> asyncMultiAddrs = findStringInMemory("AsyncWriteUSBDataPipeMulti Error");
        for (Address addr : asyncMultiAddrs) {
            Set<Function> funcs = findFunctionsReferencing(addr);
            for (Function func : funcs) {
                output.append(String.format("\nCallers of %s (AsyncWriteUSBDataPipeMulti):\n",
                    func.getName()));
                Set<Function> callers = func.getCallingFunctions(monitor);
                for (Function caller : callers) {
                    output.append(String.format("  0x%s (%s)\n",
                        caller.getEntryPoint(), caller.getName()));
                }
            }
        }

        // Summary
        output.append(String.format("\n\n=== SUMMARY: %d functions decompiled, %d failed ===\n",
                      successCount, failCount));

        // Write output
        String outDir = getSourceFile().getParentFile().getAbsolutePath();
        String outPath = outDir + File.separator + "usb_transport_decompiled.txt";
        PrintWriter pw = new PrintWriter(new FileWriter(outPath));
        pw.print(output.toString());
        pw.close();

        decomp.dispose();
        printf("Wrote %d chars (%d functions, %d failed) to %s%n",
               output.length(), successCount, failCount, outPath);
    }

    private void findAndDecompileByString(String searchStr, String description) {
        output.append(String.format("\n--- String: \"%s\" (%s) ---\n", searchStr, description));

        List<Address> addrs = findStringInMemory(searchStr);
        if (addrs.isEmpty()) {
            output.append("  NOT FOUND in firmware\n");
            return;
        }

        for (Address addr : addrs) {
            output.append(String.format("  Found at: 0x%s\n", addr));

            Set<Function> funcs = findFunctionsReferencing(addr);

            if (funcs.isEmpty()) {
                // Try pointer-based xref
                funcs = findFunctionsViaPointer(addr);
            }

            if (funcs.isEmpty()) {
                // Try finding nearest function
                Function nearest = findNearestFunction(addr);
                if (nearest != null) {
                    output.append(String.format("  No xrefs, nearest function: %s @ 0x%s\n",
                        nearest.getName(), nearest.getEntryPoint()));
                    decompileAt(nearest.getEntryPoint().getOffset(), 0);
                } else {
                    output.append("  No referencing functions found\n");
                }
            } else {
                for (Function func : funcs) {
                    output.append(String.format("  Referenced by: %s @ 0x%s\n",
                        func.getName(), func.getEntryPoint()));
                    decompileAt(func.getEntryPoint().getOffset(), 0);
                }
            }
        }
    }

    private List<Address> findStringInMemory(String searchStr) {
        List<Address> results = new ArrayList<>();
        Memory mem = currentProgram.getMemory();
        byte[] pattern = searchStr.getBytes();
        Address start = currentProgram.getMinAddress();
        try {
            while (start != null && results.size() < 10) {
                Address found = mem.findBytes(start, pattern, null, true, monitor);
                if (found == null) break;
                results.add(found);
                start = found.add(1);
            }
        } catch (Exception e) { /* ignore */ }
        return results;
    }

    private Set<Function> findFunctionsReferencing(Address addr) {
        Set<Function> funcs = new LinkedHashSet<>();
        ReferenceIterator refs = currentProgram.getReferenceManager().getReferencesTo(addr);
        while (refs.hasNext()) {
            Reference ref = refs.next();
            Function func = currentProgram.getFunctionManager().getFunctionContaining(ref.getFromAddress());
            if (func != null) funcs.add(func);
        }
        return funcs;
    }

    private Set<Function> findFunctionsViaPointer(Address strAddr) {
        Set<Function> funcs = new LinkedHashSet<>();
        long addrVal = strAddr.getOffset();
        byte[] ptrBytes = new byte[] {
            (byte)(addrVal & 0xFF), (byte)((addrVal >> 8) & 0xFF),
            (byte)((addrVal >> 16) & 0xFF), (byte)((addrVal >> 24) & 0xFF)
        };

        Memory mem = currentProgram.getMemory();
        Address start = currentProgram.getMinAddress();
        try {
            int count = 0;
            while (start != null && count < 20) {
                Address found = mem.findBytes(start, ptrBytes, null, true, monitor);
                if (found == null) break;
                count++;

                ReferenceIterator refs = currentProgram.getReferenceManager().getReferencesTo(found);
                while (refs.hasNext()) {
                    Reference ref = refs.next();
                    Function func = currentProgram.getFunctionManager().getFunctionContaining(ref.getFromAddress());
                    if (func != null) funcs.add(func);
                }
                start = found.add(1);
            }
        } catch (Exception e) { /* ignore */ }
        return funcs;
    }

    private Function findNearestFunction(Address addr) {
        FunctionManager fm = currentProgram.getFunctionManager();
        Function func = fm.getFunctionContaining(addr);
        if (func != null) return func;

        Address search = addr;
        for (int i = 0; i < 2048; i++) {
            search = search.subtract(1);
            func = fm.getFunctionAt(search);
            if (func != null) return func;
        }
        return null;
    }

    private void decompileAt(long addr, int depth) {
        if (visited.contains(addr)) return;
        if (depth > MAX_DEPTH) return;
        visited.add(addr);

        Address address = toAddr(addr);
        FunctionManager fm = currentProgram.getFunctionManager();
        Function func = fm.getFunctionAt(address);

        if (func == null) {
            output.append(String.format("\n// No function at 0x%08X (depth=%d)\n", addr, depth));
            failCount++;
            return;
        }

        // Header
        String indent = depth == 0 ? "========" : (depth == 1 ? "--------" : "........");
        output.append("\n\n");
        output.append(indent + indent + indent + indent + indent + "\n");
        output.append(String.format("Function: %s @ 0x%08X (size=%d bytes, depth=%d)\n",
                      func.getName(), addr, func.getBody().getNumAddresses(), depth));
        output.append(indent + indent + indent + indent + indent + "\n");

        // Callers
        Set<Function> callers = func.getCallingFunctions(monitor);
        if (!callers.isEmpty()) {
            output.append("// Called from:\n");
            int shown = 0;
            for (Function caller : callers) {
                if (shown >= 15) {
                    output.append(String.format("//   ... and %d more callers\n", callers.size() - shown));
                    break;
                }
                output.append(String.format("//   0x%s (%s)\n",
                    caller.getEntryPoint(), caller.getName()));
                shown++;
            }
        }

        // Callees
        Set<Function> callees = func.getCalledFunctions(monitor);
        if (!callees.isEmpty()) {
            output.append("// Calls:\n");
            for (Function callee : callees) {
                output.append(String.format("//   0x%s (%s)\n",
                    callee.getEntryPoint(), callee.getName()));
            }
        }
        output.append("\n");

        // Decompile
        DecompileResults results = decomp.decompileFunction(func, 60, monitor);
        if (results == null || !results.decompileCompleted()) {
            output.append(String.format("// DECOMPILATION FAILED: %s\n",
                results != null ? results.getErrorMessage() : "null result"));
            failCount++;
            return;
        }

        String cCode = results.getDecompiledFunction().getC();
        output.append(cCode);
        successCount++;

        // Scan for USB registers
        scanReferences(func);

        // Recurse into callees
        if (depth < MAX_DEPTH) {
            for (Function callee : callees) {
                long calleeAddr = callee.getEntryPoint().getOffset();
                if (calleeAddr < 0xFF800000L) continue;
                if (depth > 0 && OS_PRIMITIVES.contains(calleeAddr)) continue;
                decompileAt(calleeAddr, depth + 1);
            }
        }
    }

    private void scanReferences(Function func) {
        try {
            InstructionIterator instIter =
                currentProgram.getListing().getInstructions(func.getBody(), true);
            Set<String> ptrs = new TreeSet<>();
            while (instIter.hasNext()) {
                Instruction inst = instIter.next();
                Reference[] refs = inst.getReferencesFrom();
                for (Reference ref : refs) {
                    long target = ref.getToAddress().getOffset();

                    // USB register accesses
                    if ((target & 0xFFFF0000L) == 0xC0220000L) {
                        usbRegisters.add(String.format("0x%08X (in %s @ 0x%s, inst: %s)",
                            target, func.getName(), inst.getAddress(), inst.toString()));
                    }

                    // Function pointers and indirect register loads
                    if (ref.getReferenceType().isData() &&
                        target >= 0xFF800000L && target < 0xFFF00000L) {
                        try {
                            byte[] bytes = new byte[4];
                            currentProgram.getMemory().getBytes(ref.getToAddress(), bytes);
                            long val = (bytes[0] & 0xFFL) | ((bytes[1] & 0xFFL) << 8) |
                                       ((bytes[2] & 0xFFL) << 16) | ((bytes[3] & 0xFFL) << 24);
                            if ((val & 0xFFFF0000L) == 0xC0220000L) {
                                usbRegisters.add(String.format("0x%08X (indirect via DAT_%08x in %s)",
                                    val, target, func.getName()));
                            }
                            if (val >= 0xFF800000L && val < 0xFFF00000L) {
                                Function fpFunc = currentProgram.getFunctionManager().getFunctionAt(toAddr(val));
                                String name = fpFunc != null ? fpFunc.getName() : "unknown";
                                ptrs.add(String.format("DAT_%08x = 0x%08X (%s)", target, val, name));
                            }
                        } catch (Exception e) { /* ignore */ }
                    }
                }
            }
            if (!ptrs.isEmpty()) {
                output.append("// Function pointer references found:\n");
                for (String p : ptrs) {
                    output.append("//   " + p + "\n");
                }
            }
        } catch (Exception e) {
            output.append("// Error scanning references: " + e.getMessage() + "\n");
        }
    }
}
