// DecompileIDRPath.java — Ghidra headless script
// Decompiles sub_FF92FDF0 (possible IDR/I-frame handler) and related functions

import ghidra.app.decompiler.DecompInterface;
import ghidra.app.decompiler.DecompileResults;
import ghidra.app.script.GhidraScript;
import ghidra.program.model.address.Address;
import ghidra.program.model.listing.Function;
import ghidra.program.model.listing.FunctionManager;

import java.io.FileWriter;
import java.io.PrintWriter;

public class DecompileIDRPath extends GhidraScript {

    private static final long[][] FUNCTIONS = {
        { 0xFF92FDF0L, },  // Adjacent to MovieFrameGetter, called from msg 8
        { 0xFF85DE1CL, },  // Called from msg 2 (recording start?)
        { 0xFF85D3BCL, },  // Called from msg 5
        { 0xFF85D6CCL, },  // Called from msg 4
        { 0xFF85E28CL, },  // Called from msg 10
        { 0xFF85D218L, },  // Called from msg 7
    };

    private static final String[] NAMES = {
        "sub_FF92FDF0 — Possible IDR frame handler (msg 8, 2 params from message)",
        "sub_FF85DE1C — Recording start handler (msg 2)",
        "sub_FF85D3BC — Handler for msg 5",
        "sub_FF85D6CC — Handler for msg 4",
        "sub_FF85E28C — Handler for msg 10",
        "sub_FF85D218 — Handler for msg 7",
    };

    private static final String OUTPUT_FILE =
        "C:\\projects\\ixus870IS\\firmware-analysis\\idr_path_decompiled.txt";

    @Override
    public void run() throws Exception {
        PrintWriter out = new PrintWriter(new FileWriter(OUTPUT_FILE));
        out.println("=======================================================================");
        out.println("IDR Frame Path Investigation — Decompiled Functions");
        out.println("Firmware: Canon IXUS 870 IS / SD880 IS, version 1.01a");
        out.println("Generated by DecompileIDRPath.java (Ghidra headless)");
        out.println("=======================================================================");
        out.println();

        FunctionManager funcMgr = currentProgram.getFunctionManager();
        DecompInterface decomp = new DecompInterface();
        decomp.openProgram(currentProgram);

        for (int i = 0; i < FUNCTIONS.length; i++) {
            long addr = FUNCTIONS[i][0];
            String desc = NAMES[i];
            Address funcAddr = currentProgram.getAddressFactory()
                .getDefaultAddressSpace().getAddress(addr);

            out.println("-----------------------------------------------------------------------");
            out.printf("Function %d/%d: %s%n", i + 1, FUNCTIONS.length, desc);
            out.printf("Address: 0x%08X%n", addr);
            out.println("-----------------------------------------------------------------------");

            Function func = funcMgr.getFunctionAt(funcAddr);
            if (func == null) {
                disassemble(funcAddr);
                func = createFunction(funcAddr, null);
            }

            if (func == null) {
                out.println("[ERROR] Could not create function at this address.");
                out.println();
                continue;
            }

            out.printf("Function name in Ghidra: %s%n", func.getName());
            out.printf("Function size: %d bytes%n",
                func.getBody().getNumAddresses());
            out.println();

            DecompileResults results = decomp.decompileFunction(func, 120, monitor);
            if (results.decompileCompleted()) {
                out.println(results.getDecompiledFunction().getC());
            } else {
                out.println("[ERROR] Decompilation failed: " + results.getErrorMessage());
            }
            out.println();
        }

        decomp.dispose();
        out.close();
        println("DecompileIDRPath: Output written to " + OUTPUT_FILE);
    }
}
