// Ghidra script: Extract and parse USB descriptors from ROM
// Finds "USB PTP Device" label strings, dumps descriptor bytes, parses USB structures
// Also finds descriptor table data structures via cross-references
// Output: firmware-analysis/usb_descriptors_analyzed.txt
//
// Run headlessly:
//   analyzeHeadless C:\projects\ixus870IS\firmware-analysis\ghidra_project ixus870_101a
//     -process PRIMARY.BIN -noanalysis -scriptPath C:\projects\ixus870IS\firmware-analysis
//     -postScript DecompileUSBDescriptors.java
// @category Analysis

import ghidra.app.script.GhidraScript;
import ghidra.app.decompiler.DecompInterface;
import ghidra.app.decompiler.DecompileResults;
import ghidra.program.model.listing.Function;
import ghidra.program.model.listing.FunctionManager;
import ghidra.program.model.address.Address;
import ghidra.program.model.mem.Memory;
import ghidra.program.model.symbol.Reference;
import ghidra.program.model.symbol.ReferenceIterator;

import java.io.*;
import java.util.*;

public class DecompileUSBDescriptors extends GhidraScript {

    private DecompInterface decomp;
    private Set<Long> visited = new HashSet<>();
    private StringBuilder output = new StringBuilder();
    private int successCount = 0;
    private int failCount = 0;

    // USB descriptor type constants
    private static final int DESC_DEVICE = 1;
    private static final int DESC_CONFIGURATION = 2;
    private static final int DESC_STRING = 3;
    private static final int DESC_INTERFACE = 4;
    private static final int DESC_ENDPOINT = 5;
    private static final int DESC_DEVICE_QUALIFIER = 6;
    private static final int DESC_OTHER_SPEED_CONFIG = 7;
    private static final int DESC_INTERFACE_ASSOCIATION = 11;

    // Known descriptor label strings
    private static final String[] DESCRIPTOR_LABELS = {
        "USB PTP Device",
        "USB MTP Device",
        "Canon Digital Camera",
    };

    // Device descriptor signature: length=18, type=1
    private static final byte DESC_DEVICE_LEN = 0x12;
    private static final byte DESC_DEVICE_TYPE = 0x01;

    @Override
    public void run() throws Exception {
        decomp = new DecompInterface();
        decomp.openProgram(currentProgram);
        decomp.setSimplificationStyle("decompile");

        Memory mem = currentProgram.getMemory();

        output.append("=======================================================================\n");
        output.append("USB Descriptor Analysis — Raw Extraction + Parsing\n");
        output.append("Firmware: Canon IXUS 870 IS / SD880 IS, version 1.01a\n");
        output.append("Generated by DecompileUSBDescriptors.java (Ghidra headless)\n");
        output.append("ROM base: 0xFF810000\n");
        output.append("=======================================================================\n\n");

        output.append("KEY QUESTIONS:\n");
        output.append("1. Exact endpoint configuration (types, max packet sizes, directions)\n");
        output.append("2. Is there room for additional interfaces (UVC)?\n");
        output.append("3. How are descriptors served to the host (RAM copy or ROM direct)?\n");
        output.append("4. Are there differences between the two descriptor sets?\n\n");

        // === SECTION 1: Find descriptor label strings ===
        output.append("=======================================================================\n");
        output.append("SECTION 1: Descriptor Label Strings\n");
        output.append("=======================================================================\n\n");

        for (String label : DESCRIPTOR_LABELS) {
            List<Address> addrs = findStringInMemory(label);
            output.append(String.format("String \"%s\": %d occurrences\n", label, addrs.size()));
            for (Address addr : addrs) {
                output.append(String.format("  Found at: 0x%s (ROM offset: 0x%06X)\n",
                    addr, addr.getOffset() - 0xFF810000L));

                // Dump context bytes around the string
                dumpBytes(addr.subtract(16), 64, "Context around string");

                // Find xrefs to this string
                Set<Function> funcs = findFunctionsReferencing(addr);
                if (!funcs.isEmpty()) {
                    output.append("  Referenced by functions:\n");
                    for (Function func : funcs) {
                        output.append(String.format("    %s @ 0x%s\n",
                            func.getName(), func.getEntryPoint()));
                    }
                }

                // Look for pointer-to-string in ROM (descriptor table entries)
                findPointersTo(addr);
            }
            output.append("\n");
        }

        // === SECTION 2: Scan for USB device descriptors ===
        output.append("\n=======================================================================\n");
        output.append("SECTION 2: USB Device Descriptor Scan (signature: 0x12 0x01)\n");
        output.append("=======================================================================\n\n");

        scanForDeviceDescriptors(mem);

        // === SECTION 3: Scan for USB config descriptors ===
        output.append("\n=======================================================================\n");
        output.append("SECTION 3: USB Configuration Descriptor Scan (signature: 0x09 0x02)\n");
        output.append("=======================================================================\n\n");

        scanForConfigDescriptors(mem);

        // === SECTION 4: Known descriptor region dumps ===
        // ROM base 0xFF810000 + offsets from plan
        long set1Offset = 0xFF810000L + 0x001728E4L;  // 0xFF9828E4
        long set2Offset = 0xFF810000L + 0x0017F258L;  // 0xFF98F258

        output.append("\n=======================================================================\n");
        output.append("SECTION 4: Known Descriptor Regions (from firmware analysis)\n");
        output.append("=======================================================================\n\n");

        output.append("--- Descriptor Set 1 region (ROM offset 0x001728E4) ---\n");
        dumpAndParseRegion(toAddr(set1Offset), 512);

        output.append("\n--- Descriptor Set 2 region (ROM offset 0x0017F258) ---\n");
        dumpAndParseRegion(toAddr(set2Offset), 512);

        // === SECTION 5: Find descriptor table structures ===
        output.append("\n=======================================================================\n");
        output.append("SECTION 5: Descriptor Table Structures (xref analysis)\n");
        output.append("=======================================================================\n\n");

        findDescriptorTables();

        // === SECTION 6: Decompile descriptor-serving functions ===
        output.append("\n=======================================================================\n");
        output.append("SECTION 6: Functions that reference descriptor data\n");
        output.append("=======================================================================\n\n");

        // Find functions referencing "DianaUSBConfig.c" — these manage descriptors
        List<Address> configAddrs = findStringInMemory("DianaUSBConfig.c");
        for (Address addr : configAddrs) {
            Set<Function> funcs = findFunctionsReferencing(addr);
            for (Function func : funcs) {
                decompileAt(func.getEntryPoint().getOffset(), 0);
            }
        }

        // Also search for functions referencing "GetDescriptor"
        List<Address> getDescAddrs = findStringInMemory("GetDescriptor");
        for (Address addr : getDescAddrs) {
            output.append(String.format("String \"GetDescriptor\" at 0x%s\n", addr));
            Set<Function> funcs = findFunctionsReferencing(addr);
            for (Function func : funcs) {
                decompileAt(func.getEntryPoint().getOffset(), 0);
            }
        }

        // Search for "SetConfiguration"
        List<Address> setConfigAddrs = findStringInMemory("SetConfiguration");
        for (Address addr : setConfigAddrs) {
            output.append(String.format("String \"SetConfiguration\" at 0x%s\n", addr));
            Set<Function> funcs = findFunctionsReferencing(addr);
            for (Function func : funcs) {
                decompileAt(func.getEntryPoint().getOffset(), 0);
            }
        }

        // Summary
        output.append(String.format("\n\n=== SUMMARY: %d functions decompiled, %d failed ===\n",
                      successCount, failCount));

        // Write output
        String outDir = getSourceFile().getParentFile().getAbsolutePath();
        String outPath = outDir + File.separator + "usb_descriptors_analyzed.txt";
        PrintWriter pw = new PrintWriter(new FileWriter(outPath));
        pw.print(output.toString());
        pw.close();

        decomp.dispose();
        printf("Wrote %d chars (%d functions, %d failed) to %s%n",
               output.length(), successCount, failCount, outPath);
    }

    private void scanForDeviceDescriptors(Memory mem) {
        // Search for device descriptor signature: bLength=0x12, bDescriptorType=0x01
        byte[] pattern = new byte[] { 0x12, 0x01 };
        Address start = currentProgram.getMinAddress();
        int count = 0;
        try {
            while (start != null && count < 50) {
                Address found = mem.findBytes(start, pattern, null, true, monitor);
                if (found == null) break;

                // Validate: check bcdUSB (bytes 2-3) should be 0x0100, 0x0110, or 0x0200
                byte[] desc = new byte[18];
                mem.getBytes(found, desc);
                int bcdUSB = (desc[2] & 0xFF) | ((desc[3] & 0xFF) << 8);
                if (bcdUSB == 0x0100 || bcdUSB == 0x0110 || bcdUSB == 0x0200 || bcdUSB == 0x0201) {
                    output.append(String.format("Device descriptor at 0x%s (ROM offset 0x%06X):\n",
                        found, found.getOffset() - 0xFF810000L));
                    parseDeviceDescriptor(desc);
                    dumpBytes(found, 18, "Raw bytes");

                    // Check xrefs
                    findPointersTo(found);
                    count++;
                }
                start = found.add(1);
            }
        } catch (Exception e) {
            output.append("Error scanning: " + e.getMessage() + "\n");
        }
        output.append(String.format("Total device descriptors found: %d\n", count));
    }

    private void scanForConfigDescriptors(Memory mem) {
        // Search for config descriptor signature: bLength=0x09, bDescriptorType=0x02
        byte[] pattern = new byte[] { 0x09, 0x02 };
        Address start = currentProgram.getMinAddress();
        int count = 0;
        try {
            while (start != null && count < 50) {
                Address found = mem.findBytes(start, pattern, null, true, monitor);
                if (found == null) break;

                // Validate: wTotalLength (bytes 2-3) should be reasonable (20-500)
                byte[] hdr = new byte[9];
                mem.getBytes(found, hdr);
                int wTotalLength = (hdr[2] & 0xFF) | ((hdr[3] & 0xFF) << 8);
                int bNumInterfaces = hdr[4] & 0xFF;
                int bConfigValue = hdr[5] & 0xFF;

                if (wTotalLength >= 20 && wTotalLength <= 500 &&
                    bNumInterfaces >= 1 && bNumInterfaces <= 8 &&
                    bConfigValue >= 1 && bConfigValue <= 4) {

                    output.append(String.format("Config descriptor at 0x%s (ROM offset 0x%06X):\n",
                        found, found.getOffset() - 0xFF810000L));

                    // Read full config descriptor (including all interfaces/endpoints)
                    byte[] fullDesc = new byte[wTotalLength];
                    mem.getBytes(found, fullDesc);
                    parseConfigDescriptor(fullDesc);
                    dumpBytes(found, Math.min(wTotalLength, 256), "Raw bytes");

                    findPointersTo(found);
                    count++;
                }
                start = found.add(1);
            }
        } catch (Exception e) {
            output.append("Error scanning: " + e.getMessage() + "\n");
        }
        output.append(String.format("Total config descriptors found: %d\n", count));
    }

    private void parseDeviceDescriptor(byte[] d) {
        output.append(String.format("  bLength:            %d\n", d[0] & 0xFF));
        output.append(String.format("  bDescriptorType:    %d (DEVICE)\n", d[1] & 0xFF));
        output.append(String.format("  bcdUSB:             %d.%02d\n",
            ((d[3] & 0xFF) << 8 | (d[2] & 0xFF)) >> 8,
            (d[2] & 0xFF) & 0xFF));
        output.append(String.format("  bDeviceClass:       0x%02X\n", d[4] & 0xFF));
        output.append(String.format("  bDeviceSubClass:    0x%02X\n", d[5] & 0xFF));
        output.append(String.format("  bDeviceProtocol:    0x%02X\n", d[6] & 0xFF));
        output.append(String.format("  bMaxPacketSize0:    %d\n", d[7] & 0xFF));
        int idVendor = (d[8] & 0xFF) | ((d[9] & 0xFF) << 8);
        int idProduct = (d[10] & 0xFF) | ((d[11] & 0xFF) << 8);
        int bcdDevice = (d[12] & 0xFF) | ((d[13] & 0xFF) << 8);
        output.append(String.format("  idVendor:           0x%04X\n", idVendor));
        output.append(String.format("  idProduct:          0x%04X\n", idProduct));
        output.append(String.format("  bcdDevice:          %d.%02d\n", bcdDevice >> 8, bcdDevice & 0xFF));
        output.append(String.format("  iManufacturer:      %d\n", d[14] & 0xFF));
        output.append(String.format("  iProduct:           %d\n", d[15] & 0xFF));
        output.append(String.format("  iSerialNumber:      %d\n", d[16] & 0xFF));
        output.append(String.format("  bNumConfigurations: %d\n", d[17] & 0xFF));
    }

    private void parseConfigDescriptor(byte[] d) {
        int wTotalLength = (d[2] & 0xFF) | ((d[3] & 0xFF) << 8);
        output.append(String.format("  bLength:            %d\n", d[0] & 0xFF));
        output.append(String.format("  bDescriptorType:    %d (CONFIGURATION)\n", d[1] & 0xFF));
        output.append(String.format("  wTotalLength:       %d\n", wTotalLength));
        output.append(String.format("  bNumInterfaces:     %d\n", d[4] & 0xFF));
        output.append(String.format("  bConfigurationValue:%d\n", d[5] & 0xFF));
        output.append(String.format("  iConfiguration:     %d\n", d[6] & 0xFF));
        output.append(String.format("  bmAttributes:       0x%02X%s%s\n", d[7] & 0xFF,
            ((d[7] & 0x40) != 0) ? " (Self-powered)" : "",
            ((d[7] & 0x20) != 0) ? " (Remote Wakeup)" : ""));
        output.append(String.format("  bMaxPower:          %d mA\n", (d[8] & 0xFF) * 2));

        // Parse embedded descriptors
        int offset = 9;
        while (offset + 2 <= wTotalLength && offset + 2 <= d.length) {
            int len = d[offset] & 0xFF;
            int type = d[offset + 1] & 0xFF;

            if (len < 2 || offset + len > d.length) break;

            switch (type) {
                case DESC_INTERFACE:
                    if (len >= 9) {
                        output.append(String.format("\n  --- Interface Descriptor (offset %d) ---\n", offset));
                        output.append(String.format("    bInterfaceNumber:   %d\n", d[offset + 2] & 0xFF));
                        output.append(String.format("    bAlternateSetting:  %d\n", d[offset + 3] & 0xFF));
                        output.append(String.format("    bNumEndpoints:      %d\n", d[offset + 4] & 0xFF));
                        int ifClass = d[offset + 5] & 0xFF;
                        int ifSubClass = d[offset + 6] & 0xFF;
                        int ifProtocol = d[offset + 7] & 0xFF;
                        output.append(String.format("    bInterfaceClass:    0x%02X (%s)\n",
                            ifClass, getClassName(ifClass)));
                        output.append(String.format("    bInterfaceSubClass: 0x%02X\n", ifSubClass));
                        output.append(String.format("    bInterfaceProtocol: 0x%02X\n", ifProtocol));
                        output.append(String.format("    iInterface:         %d\n", d[offset + 8] & 0xFF));
                    }
                    break;

                case DESC_ENDPOINT:
                    if (len >= 7) {
                        output.append(String.format("\n  --- Endpoint Descriptor (offset %d) ---\n", offset));
                        int epAddr = d[offset + 2] & 0xFF;
                        int epAttrs = d[offset + 3] & 0xFF;
                        int maxPacket = (d[offset + 4] & 0xFF) | ((d[offset + 5] & 0xFF) << 8);
                        int interval = d[offset + 6] & 0xFF;
                        String dir = ((epAddr & 0x80) != 0) ? "IN" : "OUT";
                        int epNum = epAddr & 0x0F;
                        String xferType;
                        switch (epAttrs & 0x03) {
                            case 0: xferType = "Control"; break;
                            case 1: xferType = "Isochronous"; break;
                            case 2: xferType = "Bulk"; break;
                            case 3: xferType = "Interrupt"; break;
                            default: xferType = "Unknown"; break;
                        }
                        output.append(String.format("    bEndpointAddress:   0x%02X (EP%d %s)\n",
                            epAddr, epNum, dir));
                        output.append(String.format("    bmAttributes:       0x%02X (%s)\n",
                            epAttrs, xferType));
                        output.append(String.format("    wMaxPacketSize:     %d\n", maxPacket));
                        output.append(String.format("    bInterval:          %d\n", interval));

                        if ((epAttrs & 0x03) == 1) {
                            output.append("    *** ISOCHRONOUS ENDPOINT FOUND! ***\n");
                        }
                    }
                    break;

                case DESC_INTERFACE_ASSOCIATION:
                    if (len >= 8) {
                        output.append(String.format("\n  --- Interface Association Descriptor (offset %d) ---\n", offset));
                        output.append(String.format("    bFirstInterface:    %d\n", d[offset + 2] & 0xFF));
                        output.append(String.format("    bInterfaceCount:    %d\n", d[offset + 3] & 0xFF));
                        output.append(String.format("    bFunctionClass:     0x%02X\n", d[offset + 4] & 0xFF));
                        output.append(String.format("    bFunctionSubClass:  0x%02X\n", d[offset + 5] & 0xFF));
                        output.append(String.format("    bFunctionProtocol:  0x%02X\n", d[offset + 6] & 0xFF));
                        output.append(String.format("    iFunction:          %d\n", d[offset + 7] & 0xFF));
                    }
                    break;

                default:
                    output.append(String.format("\n  --- Unknown Descriptor type=%d len=%d (offset %d) ---\n",
                        type, len, offset));
                    break;
            }
            offset += len;
        }
    }

    private String getClassName(int classCode) {
        switch (classCode) {
            case 0x00: return "Defined at Interface level";
            case 0x01: return "Audio";
            case 0x02: return "CDC-Control";
            case 0x03: return "HID";
            case 0x06: return "Still Image (PTP)";
            case 0x08: return "Mass Storage";
            case 0x09: return "Hub";
            case 0x0A: return "CDC-Data";
            case 0x0E: return "Video (UVC)";
            case 0xEF: return "Misc (IAD)";
            case 0xFF: return "Vendor Specific";
            default: return "Unknown";
        }
    }

    private void dumpAndParseRegion(Address addr, int length) {
        Memory mem = currentProgram.getMemory();
        try {
            // Check if address is valid
            if (!mem.contains(addr)) {
                output.append(String.format("  Address 0x%s not in memory!\n", addr));
                return;
            }

            output.append(String.format("Region at 0x%s (ROM offset 0x%06X), %d bytes:\n",
                addr, addr.getOffset() - 0xFF810000L, length));

            // Read the region
            byte[] data = new byte[length];
            int bytesRead = mem.getBytes(addr, data);

            // Hex dump
            dumpBytesRaw(data, bytesRead, addr.getOffset());

            // Try to parse as a sequence of USB descriptors
            output.append("\n  Descriptor parse attempt:\n");
            int offset = 0;
            int descCount = 0;
            while (offset + 2 <= bytesRead) {
                int len = data[offset] & 0xFF;
                int type = data[offset + 1] & 0xFF;

                if (len < 2 || len > 255 || type == 0) break;
                if (offset + len > bytesRead) break;

                // Check if this looks like a valid USB descriptor
                if (type == DESC_DEVICE && len == 18) {
                    output.append(String.format("  [offset 0x%X] Device Descriptor:\n", offset));
                    byte[] desc = Arrays.copyOfRange(data, offset, offset + len);
                    parseDeviceDescriptor(desc);
                    descCount++;
                } else if (type == DESC_CONFIGURATION && len == 9) {
                    int wTotal = (data[offset + 2] & 0xFF) | ((data[offset + 3] & 0xFF) << 8);
                    output.append(String.format("  [offset 0x%X] Config Descriptor (wTotalLength=%d):\n", offset, wTotal));
                    if (offset + wTotal <= bytesRead) {
                        byte[] desc = Arrays.copyOfRange(data, offset, offset + wTotal);
                        parseConfigDescriptor(desc);
                        offset = offset + wTotal;
                        descCount++;
                        continue;
                    }
                    descCount++;
                } else if (type == DESC_STRING) {
                    output.append(String.format("  [offset 0x%X] String Descriptor (len=%d):\n", offset, len));
                    if (len > 2) {
                        StringBuilder str = new StringBuilder();
                        for (int i = 2; i < len && i + 1 < data.length; i += 2) {
                            char c = (char)((data[offset + i] & 0xFF) | ((data[offset + i + 1] & 0xFF) << 8));
                            if (c >= 0x20 && c < 0x7F) str.append(c);
                            else str.append('.');
                        }
                        output.append(String.format("    String: \"%s\"\n", str.toString()));
                    }
                    descCount++;
                } else if (type == DESC_DEVICE_QUALIFIER && len == 10) {
                    output.append(String.format("  [offset 0x%X] Device Qualifier Descriptor:\n", offset));
                    descCount++;
                } else if (type <= 15 && len <= 64) {
                    output.append(String.format("  [offset 0x%X] Descriptor type=%d len=%d\n", offset, type, len));
                    descCount++;
                } else {
                    // Doesn't look like a descriptor anymore
                    break;
                }
                offset += len;
            }
            output.append(String.format("  Parsed %d descriptors, stopped at offset 0x%X\n", descCount, offset));

        } catch (Exception e) {
            output.append("  Error reading region: " + e.getMessage() + "\n");
        }
    }

    private void dumpBytes(Address addr, int length, String label) {
        Memory mem = currentProgram.getMemory();
        try {
            if (!mem.contains(addr)) return;
            byte[] data = new byte[length];
            int bytesRead = mem.getBytes(addr, data);
            output.append(String.format("  %s at 0x%s (%d bytes):\n", label, addr, bytesRead));
            dumpBytesRaw(data, bytesRead, addr.getOffset());
        } catch (Exception e) {
            output.append("  Error reading bytes: " + e.getMessage() + "\n");
        }
    }

    private void dumpBytesRaw(byte[] data, int length, long baseAddr) {
        for (int i = 0; i < length; i += 16) {
            output.append(String.format("  %08X: ", baseAddr + i));
            StringBuilder ascii = new StringBuilder();
            for (int j = 0; j < 16 && i + j < length; j++) {
                output.append(String.format("%02X ", data[i + j] & 0xFF));
                char c = (char)(data[i + j] & 0xFF);
                ascii.append(c >= 0x20 && c < 0x7F ? c : '.');
            }
            // Pad if short line
            for (int j = length - i; j < 16; j++) {
                output.append("   ");
            }
            output.append(" |" + ascii.toString() + "|\n");
        }
    }

    private void findDescriptorTables() {
        // Look for structured tables that reference descriptors
        // Canon firmware typically has a table of {type, pointer, length} entries
        Memory mem = currentProgram.getMemory();

        // Search for the string "USB PTP Device" and find pointers to it in ROM
        List<Address> labelAddrs = findStringInMemory("USB PTP Device");
        for (Address labelAddr : labelAddrs) {
            output.append(String.format("\nSearching for pointers to label at 0x%s:\n", labelAddr));

            long val = labelAddr.getOffset();
            byte[] ptrBytes = new byte[] {
                (byte)(val & 0xFF), (byte)((val >> 8) & 0xFF),
                (byte)((val >> 16) & 0xFF), (byte)((val >> 24) & 0xFF)
            };

            Address searchStart = currentProgram.getMinAddress();
            try {
                int found = 0;
                while (searchStart != null && found < 20) {
                    Address ptrLoc = mem.findBytes(searchStart, ptrBytes, null, true, monitor);
                    if (ptrLoc == null) break;

                    output.append(String.format("  Pointer at 0x%s (ROM offset 0x%06X)\n",
                        ptrLoc, ptrLoc.getOffset() - 0xFF810000L));

                    // Dump context: the table structure around this pointer
                    dumpBytes(ptrLoc.subtract(32), 128, "Table context");

                    // Try to interpret as a descriptor table entry
                    // Common format: { char* label, descriptor_t* descriptors, int count }
                    byte[] tableEntry = new byte[32];
                    mem.getBytes(ptrLoc.subtract(8), tableEntry);
                    output.append("  Possible table entry interpretation:\n");
                    for (int off = 0; off < 24; off += 4) {
                        long word = (tableEntry[off] & 0xFFL) | ((tableEntry[off+1] & 0xFFL) << 8) |
                                    ((tableEntry[off+2] & 0xFFL) << 16) | ((tableEntry[off+3] & 0xFFL) << 24);
                        output.append(String.format("    [%+d]: 0x%08X", off - 8, word));
                        if (word >= 0xFF810000L && word < 0xFFF00000L) {
                            output.append(" (ROM pointer)");
                        } else if (word > 0 && word < 256) {
                            output.append(String.format(" (small value: %d)", word));
                        }
                        output.append("\n");
                    }

                    // Decompile any function that references this table location
                    ReferenceIterator refs = currentProgram.getReferenceManager().getReferencesTo(ptrLoc);
                    while (refs.hasNext()) {
                        Reference ref = refs.next();
                        Function func = currentProgram.getFunctionManager().getFunctionContaining(ref.getFromAddress());
                        if (func != null) {
                            output.append(String.format("  Referenced by %s @ 0x%s\n",
                                func.getName(), func.getEntryPoint()));
                            decompileAt(func.getEntryPoint().getOffset(), 0);
                        }
                    }

                    found++;
                    searchStart = ptrLoc.add(1);
                }
            } catch (Exception e) {
                output.append("  Error: " + e.getMessage() + "\n");
            }
        }
    }

    private List<Address> findStringInMemory(String searchStr) {
        List<Address> results = new ArrayList<>();
        Memory mem = currentProgram.getMemory();
        byte[] pattern = searchStr.getBytes();
        Address start = currentProgram.getMinAddress();
        try {
            while (start != null) {
                Address found = mem.findBytes(start, pattern, null, true, monitor);
                if (found == null) break;
                results.add(found);
                start = found.add(1);
            }
        } catch (Exception e) { /* ignore */ }
        return results;
    }

    private Set<Function> findFunctionsReferencing(Address addr) {
        Set<Function> funcs = new LinkedHashSet<>();
        ReferenceIterator refs = currentProgram.getReferenceManager().getReferencesTo(addr);
        while (refs.hasNext()) {
            Reference ref = refs.next();
            Function func = currentProgram.getFunctionManager().getFunctionContaining(ref.getFromAddress());
            if (func != null) funcs.add(func);
        }
        return funcs;
    }

    private void findPointersTo(Address targetAddr) {
        Memory mem = currentProgram.getMemory();
        long val = targetAddr.getOffset();
        byte[] ptrBytes = new byte[] {
            (byte)(val & 0xFF), (byte)((val >> 8) & 0xFF),
            (byte)((val >> 16) & 0xFF), (byte)((val >> 24) & 0xFF)
        };

        Address start = currentProgram.getMinAddress();
        try {
            int count = 0;
            while (start != null && count < 10) {
                Address found = mem.findBytes(start, ptrBytes, null, true, monitor);
                if (found == null) break;
                output.append(String.format("  Pointer to 0x%s found at 0x%s\n", targetAddr, found));
                count++;
                start = found.add(1);
            }
        } catch (Exception e) { /* ignore */ }
    }

    private void decompileAt(long addr, int depth) {
        if (visited.contains(addr)) return;
        if (depth > 2) return;
        visited.add(addr);

        Address address = toAddr(addr);
        Function func = currentProgram.getFunctionManager().getFunctionAt(address);
        if (func == null) {
            failCount++;
            return;
        }

        String indent = depth == 0 ? "========" : "--------";
        output.append("\n\n");
        output.append(indent + indent + indent + indent + indent + "\n");
        output.append(String.format("Function: %s @ 0x%08X (size=%d bytes, depth=%d)\n",
                      func.getName(), addr, func.getBody().getNumAddresses(), depth));
        output.append(indent + indent + indent + indent + indent + "\n");

        Set<Function> callers = func.getCallingFunctions(monitor);
        if (!callers.isEmpty()) {
            output.append("// Called from:\n");
            int shown = 0;
            for (Function caller : callers) {
                if (shown >= 10) break;
                output.append(String.format("//   0x%s (%s)\n",
                    caller.getEntryPoint(), caller.getName()));
                shown++;
            }
        }

        Set<Function> callees = func.getCalledFunctions(monitor);
        if (!callees.isEmpty()) {
            output.append("// Calls:\n");
            for (Function callee : callees) {
                output.append(String.format("//   0x%s (%s)\n",
                    callee.getEntryPoint(), callee.getName()));
            }
        }
        output.append("\n");

        DecompileResults results = decomp.decompileFunction(func, 60, monitor);
        if (results == null || !results.decompileCompleted()) {
            output.append(String.format("// DECOMPILATION FAILED: %s\n",
                results != null ? results.getErrorMessage() : "null result"));
            failCount++;
            return;
        }

        output.append(results.getDecompiledFunction().getC());
        successCount++;

        // Recurse into callees
        if (depth < 2) {
            for (Function callee : callees) {
                long calleeAddr = callee.getEntryPoint().getOffset();
                if (calleeAddr >= 0xFF800000L && calleeAddr < 0xFFF00000L) {
                    decompileAt(calleeAddr, depth + 1);
                }
            }
        }
    }
}
